### ISSUE TITLE
Add/remove nodes dynamically in a Quorum network

### ISSUE THREAD

**Issue by Jakedavies** [ClearGDPR/ClearGDPR#3] opened 2018-05-25 17:00 UTC
The system must have the ability to add or remove nodes (aka processors) from the Quorum blockchain network after it is deployed and set for the first time.

After some research, found a way to add a node in the node Geth (Quorum node) console:

```raft.addPeer($enodeInfo)```

Network must be in Raft consensus. Can later check connectivity through:

```admin.peers```

Need more testing now.

**Comment by segoddnja** [comment] 2018-07-31 12:52
@sindelio Is it not a duplicate of #309 ?

**Comment by Nelrohd** [comment] 2018-07-31 13:49
It seems, let's close for now. @sindelio Please re-open if it isn't.

**Closed by Nelrohd** 2018-07-31 13:49 UTC
Labels: blockchain, enhancement

**Comment by sindelio** [comment] 2018-07-31 14:53
It is a requirement of #309, we can put it there as a component for now
